[package]
name = "line_cardinality"
version = "3.0.0"
description = "High performance line cardinality counts and estimates"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
keywords.workspace = true
categories = []
autobenches = false
rust-version = "1.85.0"

[features]
# Ability to process data using multiple threads
parallel = ["voracious_radix_sort/voracious_multithread"]
# Features required for the benchmarks to run. This feature set is not stable and should not be used outside of running the benchmarks.
bench = ["parallel"]

[dependencies]
hashbrown = { version = "0.16", default-features = false }
voracious_radix_sort = { version = "1", default-features = false }

[dev-dependencies]
ahash = { workspace = true, default-features = false }
bstr.workspace = true
criterion.workspace = true
hashbrown = { version = "0.16", features = ["raw-entry"], default-features = false }

[[bench]]
name = "benches"
harness = false
