[package]
name = "line_cardinality"
version = "3.0.0"
description = "High performance line cardinality counts and estimates"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
keywords.workspace = true
categories = []
autobenches = false
rust-version = "1.74.1"

[dependencies]
hashbrown = { version = "0.16", default-features = false }

[dev-dependencies]
ahash = { workspace = true, default-features = false }
bstr.workspace = true
criterion.workspace = true
hashbrown = { version = "0.16", features = ["raw-entry"], default-features = false }

[[bench]]
name = "benches"
harness = false
