# This file is part of cuniq. Copyright © 2024 cuniq contributors.
# cuniq is licensed under the GNU GPL v3.0 or any later version. See LICENSE file for full text.

name: Publish
on:
  workflow_dispatch:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      CARGO_REGISTRY_TOKEN_LINE_CARDINALITY:
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Setup workflow cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish line_cardinality
        run: cargo publish --package line_cardinality --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN_LINE_CARDINALITY }}
      - name: Publish cuniq
        run: cargo publish --package cuniq
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
